name: dcase2019win
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - argh=0.26.2=py36_1001
  - astroid=1.6.5=py36_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=19.3.0=py_0
  - audioread=2.1.8=py36h9f0ad1d_2
  - autopep8=1.5.3=pyh9f0ad1d_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bcrypt=3.1.7=py36h68a101e_1
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - brotlipy=0.7.0=py36h779f372_1000
  - ca-certificates=2021.10.8=h5b45459_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.14.0=py36ha419a9e_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - cloudpickle=1.5.0=py_0
  - colorama=0.4.3=py_0
  - cpuonly=1.0=0
  - cryptography=2.9.2=py36hef61171_0
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyh787bdff_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20181111=py_0
  - docutils=0.16=py36h9f0ad1d_1
  - entrypoints=0.3=py36h9f0ad1d_1001
  - ffmpeg=4.3=ha925a31_0
  - flake8=3.8.3=py_1
  - freetype=2.10.2=hd328e21_0
  - future=0.18.2=py36h9f0ad1d_1
  - h5py=2.10.0=nompi_py36h3b971d6_103
  - hdf5=1.10.6=nompi_ha405e13_100
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.10=pyh9f0ad1d_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.7.0=py36h9f0ad1d_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2019.4=245
  - intervaltree=3.0.2=py_0
  - ipykernel=5.3.2=py36h5ca1d4c_0
  - ipython=7.16.1=py36h95af2a2_0
  - ipython_genutils=0.2.0=py_1
  - isort=5.0.9=py36h9f0ad1d_0
  - jedi=0.17.1=py36h9f0ad1d_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9d=he774522_0
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter_client=6.1.5=py_0
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - keyring=21.2.1=py36h9f0ad1d_0
  - kiwisolver=1.2.0=py36h246c5b5_0
  - lazy-object-proxy=1.5.0=py36h779f372_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.1=default_hf44288c_0
  - liblapack=3.8.0=14_mkl
  - libllvm9=9.0.1=hde8ddfe_1
  - libpng=1.6.37=hfe6a214_1
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialindex=1.9.3=he025d50_3
  - libtiff=4.1.0=h885aae3_6
  - libuv=1.40.0=he774522_0
  - llvm-tools=9.0.1=hde8ddfe_1
  - llvmdev=9.0.1=hde8ddfe_1
  - llvmlite=0.31.0=py36ha925a31_0
  - lz4-c=1.9.2=h62dcd97_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py36h68a101e_1
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py36hfa737b6_1
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py36h68a101e_1001
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hfa6e2cd_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py36h9f0ad1d_1
  - nbformat=5.0.7=py_0
  - ninja=1.10.0=h1ad3211_0
  - notebook=6.0.3=py36h9f0ad1d_1
  - numba=0.48.0=py36h47e9c7a_0
  - numpy=1.18.5=py36h4d86e3b_0
  - numpydoc=1.1.0=pyh9f0ad1d_0
  - olefile=0.46=py_0
  - openssl=1.1.1l=h8ffe710_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py36hcc50265_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py_1
  - paramiko=2.7.1=py36_0
  - parso=0.7.0=pyh9f0ad1d_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pillow=7.2.0=py36he4e95fe_1
  - pip=20.1.1=py_1
  - pluggy=0.13.1=py36h9f0ad1d_2
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - psutil=5.7.0=py36h68a101e_1
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydocstyle=5.0.2=py_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.6.1=py_0
  - pylint=1.8.4=py36_0
  - pynacl=1.3.0=py36h2fa13f4_1001
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyreadline=2.1=py36_1001
  - pyrsistent=0.16.0=py36h68a101e_0
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.10=he025d50_1009_cpython
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.4=pyh9f0ad1d_1
  - python-language-server=0.34.1=py36h9f0ad1d_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=pyh9f0ad1d_0
  - pywin32=227=py36hfa6e2cd_0
  - pywin32-ctypes=0.2.0=py36h9f0ad1d_1001
  - pywinpty=0.5.7=py36_0
  - pyzmq=19.0.1=py36h274d426_0
  - qdarkstyle=2.8.1=pyh9f0ad1d_0
  - requests=2.24.0=pyh9f0ad1d_0
  - resampy=0.2.2=py_0
  - rope=0.17.0=pyh9f0ad1d_0
  - rtree=0.9.4=py36h9a6d676_1
  - scikit-learn=0.23.1=py36h13569b7_0
  - scipy=1.5.0=py36h9439919_0
  - send2trash=1.5.0=py_0
  - setuptools=49.2.0=py36h9f0ad1d_0
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sphinx=3.1.2=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.32.3=he774522_1
  - tbb=2020.1=he980bc4_0
  - terminado=0.8.3=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hfa6e2cd_0
  - toml=0.10.1=pyh9f0ad1d_0
  - tornado=6.0.4=py36hfa6e2cd_0
  - tqdm=4.47.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typing_extensions=4.1.1=pyha770c72_0
  - ujson=1.35=py36hbd05846_1002
  - urllib3=1.25.9=py_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - watchdog=0.10.3=py36h9f0ad1d_0
  - wcwidth=0.2.5=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36_1003
  - winpty=0.4.3=4
  - wrapt=1.12.1=py36h68a101e_1
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - yapf=0.29.0=py_0
  - youtube-dl=2020.6.16.1=py36h9f0ad1d_0
  - zeromq=4.3.2=ha925a31_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=h9f78265_3
  - pip:
    - dcase-util==0.2.16
    - librosa==0.7.2
    - pydot-ng==2.0.0
    - pyyaml==5.3.1
    - sed-eval==0.2.1
    - soundfile==0.10.3.post1
    - validators==0.15.0
prefix: dcase2019win

